project:
  type: website

website:
  title: "Xallax's Portfolio"
  navbar:
    tools:
      - icon: github
        text: Repository
        href: https://github.com/iamxallax
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true



